layout_spectrum: 0.9516129
typography_spectrum: 0
color:
  saturation: 0.517894
  lightness: 0.3451848
  brandStrength: 0.6630824
  brandColors:
    - '#948580'
    - '#020001'
    - '#DAD8D8'
    - '#5B4D44'
    - '#B0A7A4'
  rhythmicContrast: 0.2245001
name: EuroBikeClub
